import React from "react";
import Typography from '@material-ui/core/Typography';
import Link from '@material-ui/core/Link';
import { makeStyles } from '@material-ui/core/styles';

function Copyright() {
    return (
      <>
      <br/>
      <Typography variant="body2" color="textSecondary">
        {'Copyright © '}
        <Link color="inherit" href="https://www.uuidgenerator.info/">
          UUID Generator
        </Link>{' '}
        {new Date().getFullYear()}
        {'.'}
      </Typography>
      </>
    );
  }

  function Terms(){
    return(
      <>
      <br/>
      <Typography variant="subtitle1"  color="textSecondary">
        Terms
      </Typography>
      <Typography variant="body2"  color="textSecondary" component="p">The UUIDs generated doesn't have any guarantee to be unique, so use them at your own risk. You are the only one responsible for using the  UUIDs generated by this website. Only if you understood and agree to these terms you can use this website.</Typography>
      </>
    );
  };


const useStyles = makeStyles(theme => ({
    footer: {
        backgroundColor: theme.palette.background.paper,
        padding: theme.spacing(6),
      }
}));

export const Footer = () => {
  const classes = useStyles();
  return (
    <footer className={classes.footer}>
          <Typography variant="body2"  color="textSecondary" component="p">
            The UUIDs codes are generated using AWS Lambda using this <Link  href="https://github.com/uuidjs/uuid#readme">NodeJs UUID library</Link>.
          </Typography>
          <Terms/>
          <Copyright />
          <Typography variant="body2" color="textSecondary" align="right">Ver. {global.appVersion}</Typography>
    </footer>
  );
};
export default Footer;